version: '3'
services:
    app_dev:
        container_name: app_dev
        build:
            context: ..
            dockerfile: docker-files/Dockerfile.app
        working_dir: /usr/app
        command: npm run dev
        volumes:
            - ../src:/usr/app/src
        env_file:
            - ../.env.local
        ports:
            - "${PORT}:${PORT}"
        environment:
            - ENVIRONMENT=development
        restart: on-failure
    swagger:
        container_name: swagger_ui_container
        image: swaggerapi/swagger-ui
        ports:
            - "${SWAGGER_PORT}:8080"
        volumes:
            - ./doc:/usr/share/nginx/html/doc
        environment:
            API_URL: doc/openapi.yaml
            BASE_URL: "/docs"