version: '3'
services:
    app:
        container_name: app
        build:
            context: ..
            dockerfile: docker-files/Dockerfile.app
        working_dir: /usr/app
        command: npm run start
        ports:
            - "${PORT}:${PORT}"
        env_file:
            - ../.env
        restart: on-failure